### ISSUE TITLE
Pre trained weights and training

### ISSUE THREAD

**Issue by vrk7** [myselfbritty/eets_3stage#1]
Hi,

Its mentioned pre-trained weights folder is there, but it's not visible.
Also, it is not training after the first step? 
only giving a comment - Command: CUDA_VISIBLE_DEVICES=0 python tools/train.py ./configs/S3NET_S1_2/EETS/test
Can you please help?

**Comment by myselfbritty** [comment]
Hello,
Have updated the link with the pre-trained weights.
